{{- if .Values.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
    spec:
      containers:
        - name: {{ .Values.apiGateway.name }}
          image: {{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.apiGateway.service.port }}
          resources:
            requests:
              memory: {{ .Values.apiGateway.resources.requests.memory | quote }}
              cpu: {{ .Values.apiGateway.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.apiGateway.resources.limits.memory | quote }}
              cpu: {{ .Values.apiGateway.resources.limits.cpu | quote }}
          env:
            - name: GATEWAY_HTTP_ADDR
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_HTTP_ADDR
                  name: app-config
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_ENDPOINT
                  name: app-config
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
            - name: STRIPE_WEBHOOK_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: stripe-webhook-key
            - name: TRIP_SERVICE_URL
              value: "{{ .Values.tripService.name }}:{{ .Values.tripService.service.port }}"
            - name: DRIVER_SERVICE_URL
              value: "{{ .Values.driverService.name }}:{{ .Values.driverService.service.port }}"
{{- end }}
