{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.port }}
  selector:
    app: {{ .Values.apiGateway.name }}
{{- end }}
