{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: {{ .Values.rabbitmq.name | quote }}
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
    spec:
      containers:
        - name: {{ .Values.rabbitmq.name }}
          image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
          ports:
            - containerPort: {{ .Values.rabbitmq.service.amqpPort }}
            - containerPort: {{ .Values.rabbitmq.service.managementPort }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_running"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_running"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
          resources:
            requests:
              memory: {{ .Values.rabbitmq.resources.requests.memory | quote }}
              cpu: {{ .Values.rabbitmq.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.rabbitmq.resources.limits.memory | quote }}
              cpu: {{ .Values.rabbitmq.resources.limits.cpu | quote }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: RABBITMQ_MNESIA_BASE
              value: /var/lib/rabbitmq/mnesia
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
      namespace: {{ .Values.global.namespace }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
{{- end }}
