{{- if .Values.secrets.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.secrets.rabbitmq.username | quote }}
  password: {{ .Values.secrets.rabbitmq.password | quote }}
  uri: {{ .Values.secrets.rabbitmq.uri | quote }}
{{- end }}
{{- if .Values.secrets.externalApis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  osrm: {{ .Values.secrets.externalApis.osrm | quote }}
{{- end }}
---
{{- if .Values.secrets.stripe.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  stripe-secret-key: {{ .Values.secrets.stripe.secretKey | quote }}
  stripe-webhook-key: {{ .Values.secrets.stripe.webhookKey | quote }}
{{- end }}
---
{{- if .Values.secrets.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  uri: {{ .Values.secrets.mongodb.uri | quote }}
{{- end }}
