{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.jaeger.name }}
  ports:
    {{- range .Values.jaeger.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- end }}
  type: ClusterIP
{{- end }}
