{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.web.name }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
      name: http
  type: {{ .Values.web.service.type }}
{{- end }}
